### ISSUE TITLE
Landmarks (Annotated dataset)

### ISSUE THREAD

**Issue by xsacha** [borhanMorphy/fastface#1]
Is it possible to use an annotated dataset with landmarks so we can train with landmarks? The base dataset isn't very good.

**Comment by borhanMorphy** [comment]
hi @xsacha , i'm going to add some other datasets to perform landmark prediction, but i'm trying to achieve paper results first which can take a while, so lets keep this issue open until that time.

**Comment by borhanMorphy** [comment]
Most of the open-source datasets do not contain landmarks. I'm not planning landmark support in the near future, but eventually, I'll add landmark support.
