### ISSUE TITLE
Update requirements.text scipy version

### ISSUE THREAD

**Issue by ananyahjha93** [borhanMorphy/fastface#3]
Hi @borhanMorphy ,

Is there a reason for a using a specific version of scipy in requirements.txt. Can we update it to the latest?

I am getting the following error while trying to install ``scipy==1.4.1``. 

![image](https://user-images.githubusercontent.com/7491256/134527582-e64d76b3-fe36-4821-b79c-e1fbc6008ea0.png)

**Comment by borhanMorphy** [comment]
Hey @ananyahjha93 ,

thank you for reporting that. It appears that there aren't any `scipy` distributions when using `python 3.9` . I just release a new patch `0.1.3`. It should solve your problem. Update the package with `pip install fastface -U`.

Let me know if the problem occurs again.

**Comment by ananyahjha93** [comment]
Thanks @borhanMorphy. This was helpful. I am finishing up the Flash task-a-thon PR for integrating this library. Just adding tests and then it should be good to go.

**Comment by borhanMorphy** [comment]
> Thanks @borhanMorphy. This was helpful. I am finishing up the Flash task-a-thon PR for integrating this library. Just adding tests and then it should be good to go.

Oh, thanks! Glad to hear that
